apiVersion: v1
kind: Secret
metadata:
  name: stellar-indigopay-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  DATABASE_URL: "postgres://{{ .Values.secrets.postgresUser }}:{{ .Values.secrets.postgresPassword }}@postgres-svc:5432/{{ .Values.secrets.postgresDb }}"
  POSTGRES_REPLICATION_USER: {{ .Values.secrets.postgresReplicationUser | quote }}
  POSTGRES_REPLICATION_PASSWORD: {{ .Values.secrets.postgresReplicationPassword | quote }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
  ADMIN_API_KEY: {{ .Values.secrets.adminApiKey | quote }}
  METRICS_BEARER_TOKEN:
    {{ .Values.secrets.metricsBearerToken | default "" | quote }}
